name: erpnext
services:

  backend:
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql

  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
        required: true
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: "${FRAPPE_SITE_NAME_HEADER}"
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: ghcr.io/marcag3/erpnext-custom:main
    networks:
      home-server_proxy:
      default:
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  redis-cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}

  redis-queue:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}

  scheduler:
    command:
      - bench
      - schedule
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    image: ghcr.io/marcag3/erpnext-custom:main
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites


  configurator:
    image: ghcr.io/marcag3/erpnext-custom:main
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    # add redis_socketio for backward compatibility
    command:
      - >
        ls -1 apps > sites/apps.txt;
        echo "{}" > sites/common_site_config.json;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=$$DB_PASSWORD --install-app erpnext --set-default frontend;
        bench --site frontend install-app hrms;
        bench --site frontend install-app payments;
        bench --site frontend install-app print_designer;
        bench --site frontend install-app insights;
        bench --site frontend install-app builder;
    environment:
      DB_HOST: "db"
      DB_PORT: "3306"
      REDIS_CACHE: "redis-cache:6379"
      REDIS_QUEUE: "redis-queue:6379"
      SOCKETIO_PORT: "9000"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
        
networks:
  default:
    name: erpnext
  home-server_proxy:
    external: true
volumes:
  redis-cache-data:
    name: frappe_docker_redis-cache-data
  redis-queue-data:
    name: frappe_docker_redis-queue-data